baseurl:
releasev2: https://github.com/google/ExoPlayer/tree/release-v2
exo_sdk: /doc/reference/com/google/android/exoplayer2
android_sdk: https://developer.android.com/reference
excerpt_separator: <!--more-->
